### ISSUE TITLE
Add `--output` option

### ISSUE THREAD

**Issue by bchatard** [cnumr/ecoindex_cli#15]
Hi,

Is it possible to add an `--output` option to set file location/name for the report?

Thanks,

**Comment by vvatelot** [comment]
Hello @bchatard , yes I will do it

**Comment by vvatelot** [comment]
@bchatard is it urgent or can you wait for a week :question:

**Comment by bchatard** [comment]
I can wait, it's not a problem. Thanks for your help :)

**Comment by vvatelot** [comment]
OK, I can do it quickly, but I have a workshop next week and I would like to involve more people on this. As this is a good first issue... :smiley:

**Comment by vvatelot** [comment]
Hello @bchatard I made a PR for your issue : #55 can you have a look at it ?
