### ISSUE TITLE
[Feature]: Evaluate pages that requires authentication

### ISSUE THREAD

**Issue by benel** [cnumr/ecoindex_cli#212]
For most Web applications, exploring pages without giving any credential results in HTML pages with no real contents (lesser DOM elements, lesser bytes, and sometimes lesser requests). In this situation, the ecoindex seems far better than what it is for real use.

`exo_index_cli` could have a new feature in which a session cookie would be set before analysing pages. For this feature, we should provide to the command:
- the "form action" URI,
- a credential string (formatted in JSON, XML, www-form-url-encoded...).

**Comment by vvatelot** [comment]
Today, when a page requires authentication, if it is correctly implemented and returns a 401 response (or other error code) and ecoindex throws an error in this case.

But why not. This could be interesting. I flag this as enhancement, but I will not have time to work on this right now...
