### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by revolunet** [cnumr/ecoindex_cli#252]
### What happened?

Hi,

are-you interested in a PR to build and publish the docker image ?
it could be hosted for free on GitHub packages

### Version

^3.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Hello @revolunet thank you very much for your proposal!
I was working on this feature at the same time and made improvments on docker image. I published a Docker image to Docker hub here: https://hub.docker.com/r/vvatelot/ecoindex-cli

Did you have something particular in mind?

**Comment by revolunet** [comment]
Awesome thanks, will definitely use it to produce reports for some websites
