### ISSUE TITLE
[Bug]: saturation mémoire et freeze pc

### ISSUE THREAD

**Issue by simonvdfr** [cnumr/ecoindex_cli#327]
### What happened?

Hello,

Lors de l'utilisation du script, l'occupation mémoire ne fait que monter. Quand il y a plus de 100 URL mes 12 Go de Ram sont occupés, ça utilise le swap et mon pc freeze au bout d'un moment (il est quasiment inutilisable lors de l'utilisation du script, le cpu étant à 100% sur les 2 coeurs / 4 threads).
J'ai installé docker et la dernière version. Visiblement il y a beaucoup de process Chrome de lancer, peut-être qu'il ne se ferme pas après avoir audité une page ce qui sature la mémoire ?

### Version

^3.6

### What OS do you use?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Bonjour @simonvdfr merci pour cette remontée d'utilisation.
Peux tu en dire plus sur l'usage que tu en fais: S'agit il de la version docker ou du script python directement ?

**Comment by simonvdfr** [comment]
Les 2.
Sur ma machine de travail j'avais la vielle version que j'exécutais avec python 3.1 (sous Linux mint 21.2, mate 1.26), ça gonflait vite pour arriver à saturation.
Là, je viens de mettre la version Docker sur un autre pc où j'ai fait une installe de Linux mint mate (dernière version) pour faire spécialement les bench (sans rien installer d'autre) et ça fait le même problème (malgré les 16 Go de ram). Il y a énormément de process chrome quand je fais un top (plus d'une 20ène en permanence), même quand je demande une exécution sur 4 threads.

**Comment by vvatelot** [comment]
Bonjour @simonvdfr désolé pour le délai de réponse.
J'ai l'impression qu'il y a eu des régressions sur les dernières versions sans pour autant être capable de réellement reproduire le problème chez moi... Pourrais tu essayer une version de l'image docker plus ancienne à tout hasard ? https://hub.docker.com/r/vvatelot/ecoindex-cli/tags (par exemple, la 2.20.1...?)

Pour le fait qu'il y'aie beaucoup de process chrome ouverts, c'est à moitié normal: Quand tu ouvres un navigateur chrome il lance plusieurs process (jusque là tout va bien). Mais les process ne sont pas fermés proprement une fois l'analyse finie... Ça faisait l'objet d'un autre bug que je n'ai malheureusement toujours pas eu le temps de traiter...

**Comment by simonvdfr** [comment]
J'ai testé avec la 2.20.1, et là c'est stable, le process prend 1go, ça monte et redescend. par contre le compteur n'avançait pas et j'ai eu une erreur qui fait que ça n'a pas abouti au bout de 9 minute pour 250 url (ici le résultat de l'erreur que j'ai eu dans le terminal, le log était vide :
https://www.swisstransfer.com/d/b67ed07f-217c-4e04-a2c2-02289adcbc7b ).

Pour tester parfois je fais une clé usb bootable avec mint dessus et une fois booté j'install docker + ecoindex-cli

**Comment by simonvdfr** [comment]
@vvatelot tu as des nouvelles sur ce problème ?

**Comment by vvatelot** [comment]
Hello @simonvdfr peux tu tester cette version de l'image docker ? vvatelot/ecoindex-cli:playwright-chromium

**Comment by simonvdfr** [comment]
@vvatelot Je viens de tester et ça marche nickel. 900 URL avec 1 Go de RAM prise de façon stable et aucun crash !
Aussi le CPU est beaucoup moins sollicité, je dépasse rarement les 30 % d'usage lors de l'exécution.
Bravo et merci pour ton travail :)

**Comment by vvatelot** [comment]
Merci @simonvdfr pour ce retour !
Tant mieux si ça refonctionne à nouveau ! :)
