### ISSUE TITLE
'coroutine' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by mikefromlig** [cnumr/ecoindex_cli#77]
Hi,

First, thanks for this very useful tool EcoIndex !!

I'm trying to use ecoindex-cli on a mac (osx 10.13.6), with python 3.8.6, and when I enter 
`ecoindex-cli analyze --url http://www.google.fr`
I see the following error.
Please could you give me cues to solve it ?

Thanks in advance,
michael

`There are 1 url(s), do you want to process? [Y/n]: Y`
`1 urls for 1 window size`
`Processing  [####################################]  100%`
`Traceback (most recent call last):`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/ecoindex-cli", line 8, in <module>
    sys.exit(app())`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/typer/main.py", line 214, in __call__`
`    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1128, in __call__`
`    return self.main(*args, **kwargs)`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1053, in main`
`    rv = self.invoke(ctx)`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1659, in invoke`
`    return _process_result(sub_ctx.command.invoke(sub_ctx))`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1395, in invoke`
`    return ctx.invoke(self.callback, **ctx.params)`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 754, in invoke`
`    return __callback(*args, **kwargs)`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper`
`    return callback(**use_params)  # type: ignore`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ecoindex_cli/cli/app.py", line 113, in analyze`
`    write_results_to_file(filename=output_filename, results=results)`
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ecoindex_cli/files.py", line 15, in write_results_to_file`
`    headers = results[0].__dict__`
`AttributeError: 'coroutine' object has no attribute '__dict__'`
`sys:1: RuntimeWarning: coroutine 'get_page_analysis' was never awaited`

**Comment by vvatelot** [comment]
Hello @mikefromlig thanks for your feedback!
You are right: I updated the core ecoindex package to use async feature, but did not update the CLI package... My bad!
I made a fix, and you could try to update ecoindex_python with pip: `pip install --user -U ecoindex-cli`

There could be warnings while running the analysis, I'm on it...

Please, let me know...
